name: Scheduled Health Check

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run Shell Script
        id: shell_script_run
        run: bash ./health-check.sh
